version: "3"
services:
  app:
    container_name: my_movie_app
    build: .
    ports:
      - "8081:8081"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    networks:
      - myminiproject_network
    depends_on:
      - db-app

  db-app:
    container_name: myminiproject_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=username_docker
      - POSTGRES_PASSWORD=password_docker
      - POSTGRES_DB=blog
      - POSTGRES_HOST=db-app
    ports:
      - "6432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - myminiproject_network

volumes:
  api:
  database_postgres:

networks:
  myminiproject_network:
    driver: bridge